### ISSUE TITLE
메인 화면 기능 / 스타일 개발

### ISSUE THREAD

**Issue by fullyalive** [fullyalive/clone_momentum#1]
### **Normal**

- [ ] Input 스타일 분기
- [ ] favicon
- [ ] 메뉴버튼
- [ ] 링크추가

### **link.js**

- [ ] 링크 저장
- [ ] 링크 삭제
- [ ] 저장한 Link list 출력

### **todo.js**

- [x] toDo 수정할 수 있도록
- [ ] toDo 순서 최신순으로 출력되도록
- [ ] toDo 수정, 삭제 스타일링
- [ ] toDo가 없을 경우 박스가 접히도록

### **weather.js**

- [x] 날씨에 따라 아이콘 받아오기
- [x] 국가에 따라 국기 가져오기
- [ ] css 기반 flag-icon npm으로 바꾸기
- [ ] 현재 장소(locationInfo)를 클릭하면 구글 맵에서 근처의 레스토랑 혹은 유명한 장소가 표시된 지도 링크

### **focus.js**

- [x] 클릭 시 다시 focus를 설정할 수 있도록
- [x] focus localStorage에 업데이트하기

### **greeting.js**

- [x] 클릭 시 유저이름을 다시 입력
- [x] 유저이름 localStorage에 업데이트하기
